server:
  port: 8090

spring:
  application:
    name: msvc-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userDb
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


springdoc:
  api-docs:
    path: /api/user/v3/api-docs
  swagger-ui:
    path: /api/user/swagger-ui.html
